// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: '논문 정리',
      link: {type: 'generated-index', slug: '/category/논문-정리', description: '읽은 논문을 요약하고 핵심 아이디어를 정리합니다.'},
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'papers'}],
    },
    {
      type: 'category',
      label: '강의 노트',
      link: {type: 'generated-index', slug: '/category/강의-노트', description: '수강한 강의 정리 및 주요 개념 노트.'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'courses'}],
    },
    {
      type: 'category',
      label: '기술 학습',
      link: {type: 'generated-index', slug: '/category/기술-학습', description: '도구, 프레임워크, 연구에 필요한 실용 기술 노트.'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'topics'}],
    },
    {
      type: 'category',
      label: '템플릿',
      link: {type: 'generated-index', slug: '/category/templates', description: '문서를 빠르게 시작할 수 있는 템플릿 모음.'},
      collapsed: true,
      items: [{type: 'autogenerated', dirName: 'templates'}],
    },
  ],
};

export default sidebars;
